version: '3.3'
services: 
    frontend:
        build: 
            context: ./app
        command: npm start
        ports:
            - "80:8080"
        environment:
            - DEPLOY_ENV=FALSE

    server:
        build: 
            context: ./api/server
        ports:
            - "8080:8080"
        environment:
            - DEPLOY_ENV=FALSE

    auth-service:
        build:
            context: ./api/auth
        depends_on: 
            - auth-service-db
        environment: 
            - DB_URI=mysql://root:password@auth-service-db/db?charset=UTF8
            - DEPLOY_ENV=FALSE
        ports:
            - "9000:9000"

    twitch-service:
        build:
            context: ./api/twitch
        environment:
            - DEPLOY_ENV=FALSE
        ports:
            - "9001:9001"

    twitter-service:
        build:
            context: ./api/twitterb
        environment:
            - DEPLOY_ENV=FALSE
        ports:
            - "9002:9002"


    auth-service-db:
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        image: mysql:5.7.20
        ports: 
            - 0.0.0.0:7200:3306

